[package]
name = "dispo"
version = "0.1.0"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/ynuwenhof/dispo"
repository = "https://github.com/ynuwenhof/dispo"
license = "MIT OR Apache-2.0"

[dependencies]
